name: UHCGames
main: dev.tjxjnoobie.sg.Main
version: 1.0
depend: [WorldEdit, Multiverse-Core, Core]
commands:
  sg:
  survivalgames:
  crazy:
  taco:
  confirmbounty:
  who:
  list:
  bounty:
  sponsor:
  join:
  maintenance:
  speed:
  stats:
  setwins:
  debug:
  v:
  settotal:
  setkills:
  vote:
  spec:
  l:
  maprotation:
  start:
  leaderboard:
  leaderboards:
  lb:
  lbs:
  kill:
  wager:
  bid:
  kt:
  killtop:
  spoof: